[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

lib_deps = 
    https://github.com/feilipu/FreeRTOS-Arduino.git

build_flags = 
    -DUSB_SERIAL
    -DUSE_TEENSY_HW_SERIAL
    -O3
    -mfloat-abi=hard
    -mfpu=fpv5-d16
    -DARM_MATH_CM7
    -D__FPU_PRESENT=1
    -DTENSILE_FPU_FAST_MATH
    -ffast-math
    -fno-exceptions
    -fno-rtti

monitor_speed = 12000000
monitor_filters = esp8266_exception_decoder

upload_speed = 12000000
